language: node_js

node_js:
  - stable

stages:
  - express
  - staging
  - deploy
  - e2e
  - storybook

addons:
  apt:
    packages:
      - libgconf-2-4

git:
  submodules: true

services:
  - postgresql

env:
  - TRAVIS_DATABASE=$TRAVIS_DATABASE

before_script:
  - psql -c 'create database testing;' -U postgres

jobs:
  include:
    - stage: express
      name: "Express Tests"
      script:
        - npm run test
      cache:
        npm: true
      if: (NOT branch = master AND NOT branch = staging AND NOT type = pull_request)
    #  - stage: express
    #    name: "Contract tests"
    #    script:
    #      - npm run test:pact
    #    cache:
    #      npm: true
    #    if: (NOT branch = master AND NOT branch = staging AND NOT type = pull_request)
    - stage: storybook
      name: "Story book"
      script:
        - npm run storybook
      if: branch = staging
    #- stage: e2e
    #  name: "Cypress tests"
    #  script:
    #   - npm run test:ci:e2e
    #  cache:
    #    npm: true
    #    directories:
    #     - /home/travis/.cache
    # if: type = pull_request
    - stage: staging
      name: "Deploy to staging"
      script: skip
      cache:
        npm: true
        directories:
          - /home/travis/.cache
      deploy:
        provider: heroku
        app:
          staging: serene-wave-13524-staging
        api_key:
          secure: "ksKzuvCGFCtW2k3CXU0yNnMPIYZX4ybEjWM3/GwfqjJEBO5bFWf4IGYX6NZGX1Ozzm9/55UIbYRXL0UQc+ya2V4e5Mzhuey19Lii+SjPcwDvbxhmNCszVSF8KYhjeCUEc9E2f7r1zrTlIWF7StFzuH5IvlKfXzEj9QWTC3BqMHX53HTtS8b5Ev3a14LA67kA/Axe/EyjS5Q7M5MbMz8vVFv3WQmU1EiHPSoKiRrameTWT7qJFgM/KoVP5xFCMRY0MDnkfg0kJW093R6Ae6Qn4jbVVUJmS582uw1jBnhtXAPyvUVtN9C0on22mjBiEAp9dAxC7Zyc4ASAGE1vp66eOq7yBsKR0BJhXqkBnq+uRAVSzWWXf8IoPdXWPPzFDavStIii2D/phZW9QTJmpyjRZDnwUUEHaiGNBr3xuyBVD4DFNpxBqXMMUzygqUIFSJSSW3VVan4skohOcORtwMBFZePHSiFHVZQe1m1ll87UkT9EOR2M/mVD78TnIHelicA+5oodjOeB4JALkuwFtWR9izte1ydPsxWheFc2AjinoNkKWu+zqljoI+ZE8DnTU6PkUYMBtRUQRrC4SvtctCkBwqt2XoUaGH4CnckKNEm1dsDqBxKXxVXBjw+2pqdUqvZMZVKmgzVJZ9P7TmSCA2IxQKnK5A8SA+kFp5HPasnJGt8="
      if: branch = staging
    - stage: Deploy to Master
      script: skip
      deploy:
        provider: heroku
        app: serene-wave-13524
        api_key:
          secure: "ksKzuvCGFCtW2k3CXU0yNnMPIYZX4ybEjWM3/GwfqjJEBO5bFWf4IGYX6NZGX1Ozzm9/55UIbYRXL0UQc+ya2V4e5Mzhuey19Lii+SjPcwDvbxhmNCszVSF8KYhjeCUEc9E2f7r1zrTlIWF7StFzuH5IvlKfXzEj9QWTC3BqMHX53HTtS8b5Ev3a14LA67kA/Axe/EyjS5Q7M5MbMz8vVFv3WQmU1EiHPSoKiRrameTWT7qJFgM/KoVP5xFCMRY0MDnkfg0kJW093R6Ae6Qn4jbVVUJmS582uw1jBnhtXAPyvUVtN9C0on22mjBiEAp9dAxC7Zyc4ASAGE1vp66eOq7yBsKR0BJhXqkBnq+uRAVSzWWXf8IoPdXWPPzFDavStIii2D/phZW9QTJmpyjRZDnwUUEHaiGNBr3xuyBVD4DFNpxBqXMMUzygqUIFSJSSW3VVan4skohOcORtwMBFZePHSiFHVZQe1m1ll87UkT9EOR2M/mVD78TnIHelicA+5oodjOeB4JALkuwFtWR9izte1ydPsxWheFc2AjinoNkKWu+zqljoI+ZE8DnTU6PkUYMBtRUQRrC4SvtctCkBwqt2XoUaGH4CnckKNEm1dsDqBxKXxVXBjw+2pqdUqvZMZVKmgzVJZ9P7TmSCA2IxQKnK5A8SA+kFp5HPasnJGt8="
      if: branch = master
  exclude:
    - stage: staging
      if: type = pull_request
