language: node_js
node_js:
  - stable
install:
  - npm install newman
jobs:
  include:
    - stage: newman tests
      script:
        - npm run test
      cache:
        directories:
          - node_modules
    - stage: express tests
      script:
        - npm run test
      cache:
        directories:
          - node_modules
    - stage: deploy to heroku
      deploy:
        provider: heroku
        app: serene-wave-13524
        api_key:
          secure: ${HEROKU_KEY}
