language: node_js
node_js:
  - stable
install:
  - npm install newman
jobs:
  include:
    - stage: newman tests
      script:
        - newman run https://api.getpostman.com/collections/1031465-fe8c6285-c513-478c-9226-f4c8c24a56d2?apikey=${POSTMAN_KEY}
      cache:
        directories:
          - node_modules
      if: branch = staging
    - stage: express tests
      script:
        - npm run test
      cache:
        directories:
          - node_modules
    - stage: deploy to heroku
      script: skip
      deploy:
        provider: heroku
        app: serene-wave-13524
        api_key:
          secure: ${HEROKU_KEY}
