language: node_js
node_js:
  - stable
install:
  - npm install newman
stages:
  - express
  - newman
  - staging
  - deploy

jobs:
  include:
    - stage: express
      name: "Express Tests"
      script:
        - npm run test
      cache:
        directories:
          - node_modules
    - stage: staging
      name: "Deploy to staging"
      script: skip
      deploy:
        provider: heroku
        app: serene-wave-13524-staging
        api_key:
          secure: ${HEROKU_KEY}
      env: STAGING=true
      if: branch = staging
    - stage: newman
      name: "Newman tests"
      script:
        - newman run https://api.getpostman.com/collections/${POSTMAN_UID}?apikey=${POSTMAN_KEY}
      cache:
        directories:
          - node_modules
      env: STAGING=true
      if: branch = staging
    - stage: Deploy to Master
      script: skip
      deploy:
        provider: heroku
        app: serene-wave-13524
        api_key:
          secure: ${HEROKU_KEY}
      if: branch = master
  exclude:
    - stage: newman
      if: type = pull_request
    - stage: staging
      if: type = pull_request
