language: node_js

node_js:
  - stable

stages:
  - express
  - staging
  - deploy
  - e2e
  - storybook

addons:
  apt:
    packages:
      - libgconf-2-4

git:
  submodules: true

services:
  - postgresql

env:
  - TRAVIS_DATABASE=$TRAVIS_DATABASE
  - CLIENT=true
  - CLIENT=false

before_script:
  - psql -c 'create database testing;' -U postgres

jobs:
  include:
    - stage: express
      name: "Express Tests"
      script:
        - npm run test
      cache:
        npm: true
    - stage: express
      name: "Contract tests"
      script:
        - npm run test:pact
      cache:
        npm: true
    - stage: e2e
      name: "Cypress tests"
      script:
        - npm run test:ci:e2e
      cache:
        npm: true
        directories:
          - /home/travis/.cache
    - stage: storybook
      name: "Storybook"
      script:
        - cd client && npm install && npm run chromatic
      cache:
        npm: true
        directories:
          - node_modules
      env: CLIENT=true
    - stage: staging
      name: "Deploy to staging"
      script: skip
      deploy:
        provider: heroku
        app:
          staging: serene-wave-13524-staging
        api_key:
          secure: POaE5i+67DuHYwq0KIoVH/tvmXSQiFXQyoym7nWJR42Sijok+f/hikvllcVyToO99X3obuef8qYUDwUSNbglyIncfhoc/hiALeW3hPOxTX1nCsO9jBCW3nyWcTgxVTE5E72Cjsk4Mh0UJI0zlzuqZp06Dli3zDNEDjBzOvFbIpez3YuventSctgP+k3Mz4KGQZ6FJd+f2mmUplDjVKCCo6xiWP6M2GCGKpRU6XMobfxVqI5oCbhEbZPmWj1ycf2z1QRq0g1hoWW3p6EoriNwRGD1ciCHw57B70KriwKKeTsnxY1EMYsZcrhvFHN1QhhbNQDxCBRSy11RKB8ahhg3Q6U3Oj0skZH4i9lEOe7AbS2iMna07N9tjbcf/GvfaOhNc4MiAqVjEY+abe2FERZlEU1RAcnf4AyzJSs+rX5lL0wZJc70e/HndNdo38pGBViK+CDmhX6hChwrixMvq/YpZ5ZGurOTJE4mNxdCQ2gAG7/cGKhcWFEjCxMhHO/fqGNQV87/mVL8rJXZRg0W04sH4pobwCMSDSZwOXpCFYk2z6SyJY1tcP7vG1j4PyRfvTtjICTZmuHf52SDWx50l/c9X+iffkxQUyGRZ7RUXAlIt9pt3FQ/IDI2CFx/VgRyZQt4Y1bpX+E0Y+sAzSq6Jqq+V71Sb65VXT2vQ7TxI2x7LDc=
      if: branch = staging
    - stage: Deploy to Master
      script: skip
      deploy:
        provider: heroku
        app: serene-wave-13524
        api_key:
          secure: POaE5i+67DuHYwq0KIoVH/tvmXSQiFXQyoym7nWJR42Sijok+f/hikvllcVyToO99X3obuef8qYUDwUSNbglyIncfhoc/hiALeW3hPOxTX1nCsO9jBCW3nyWcTgxVTE5E72Cjsk4Mh0UJI0zlzuqZp06Dli3zDNEDjBzOvFbIpez3YuventSctgP+k3Mz4KGQZ6FJd+f2mmUplDjVKCCo6xiWP6M2GCGKpRU6XMobfxVqI5oCbhEbZPmWj1ycf2z1QRq0g1hoWW3p6EoriNwRGD1ciCHw57B70KriwKKeTsnxY1EMYsZcrhvFHN1QhhbNQDxCBRSy11RKB8ahhg3Q6U3Oj0skZH4i9lEOe7AbS2iMna07N9tjbcf/GvfaOhNc4MiAqVjEY+abe2FERZlEU1RAcnf4AyzJSs+rX5lL0wZJc70e/HndNdo38pGBViK+CDmhX6hChwrixMvq/YpZ5ZGurOTJE4mNxdCQ2gAG7/cGKhcWFEjCxMhHO/fqGNQV87/mVL8rJXZRg0W04sH4pobwCMSDSZwOXpCFYk2z6SyJY1tcP7vG1j4PyRfvTtjICTZmuHf52SDWx50l/c9X+iffkxQUyGRZ7RUXAlIt9pt3FQ/IDI2CFx/VgRyZQt4Y1bpX+E0Y+sAzSq6Jqq+V71Sb65VXT2vQ7TxI2x7LDc=
      if: branch = master
  exclude:
    - stage: staging
      if: type = pull_request
